apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-gfqtziys
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-gfqtziys:bf7ef37681f4f91bd3eb703ea6647c0d68b798fe@sha256:4ed7c7605a723570c587db5a6094d1bbea824659b6a1bd90d8566d22ca9c3cf4
          name: container-image
